# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  IVY_CACHE_FOLDER: $(Pipeline.Workspace)/.ivy2/
  SBT_IVY_OPTION: "--ivy $(IVY_CACHE_FOLDER)"

steps:
- task: Cache@2
  inputs:
    key: 'sbt | "$(Agent.OS)" | **/build.sbt'
    restoreKeys: |
      sbt | "$(Agent.OS)
      sbt
    path: $(IVY_CACHE_FOLDER)
  displayName: sbt build cache

- script: |
    echo build
    sbt $(SBT_IVY_OPTION) clean package
  displayName: Build

- script: |
    echo scaladoc
    sbt $(SBT_IVY_OPTION) doc
  displayName: Create API Document

- script: |
    echo test
    sbt $(SBT_IVY_OPTION) -Dactive.profile=ut test
  displayName: Unit Test

- script: |
    echo assembly
    sbt $(SBT_IVY_OPTION) assembly
  displayName: Create Assembly