version: 0.2


phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo build
      - sbt clean package
      - echo scaladoc_unidoc
      - sbt unidoc
      - echo unit_test
      - sbt -Dactive.profile=ut coverage test
      - echo integration_test
      - sbt -Dactive.profile=it it:test
  post_build:
    commands:
      - echo assembly
      - sbt assembly
reports:
  test_report:
    files:
      - '**/target/test-reports/*.xml'
    file-format: JUNITXML
  coverage_report:
    files:
      - 'target/**/coverage-report/cobertura.xml'
    file-format: COBERTURAXML
artifacts:
  files:
    - 'target/**/databricks_dev-assembly-*.jar'
    - 'target/**/scoverage-report/**/*'
    - 'target/**/unidoc/**/*'
cache:
  paths:
    - '/root/.m2/**/*'
    - '/root/.sbt/**/*'
    - '/root/.ivy2/**/*'