version: 0.2


phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo build
      - sbt clean package
  post_build:
    commands:
      - echo assembly
      - sbt assembly
      - echo scaladoc_unidoc
      - sbt unidoc
      - echo test
      - sbt -Dactive.profile=ut coverage test
      - echo integration_test
      - sbt -Dactive.profile=it it:test
artifacts:
  files:
    - '**/target/**/databricks_dev-assembly-*.jar'

cache:
  paths:
    - '/root/.ivy/**/*'